# -*- coding: utf-8 -*-
"""Sumfunction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pWGX6LBjrV2moq_OTvxf5YpnYXTp8jqB
"""

#Function that takes two numbers and returns the sum
def add(a,b):
  sum = a + b
  return sum

#input from user for num1
num1 = int(input("input the number one: "))
#input from user for num2
num2 = int(input("input the number one :"))

#Calling the add function and printing the result
print("The sum is",add(num1,num2))